name: 'Run'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-wm1:
    name: "Build wm1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WM1_HOST }}
          port: ${{ secrets.WM1_PORT }}
          username: ${{ secrets.WM1_USERNAME }}
          key: ${{ secrets.WM1_KEY }}
          source: "target.txt"
          target: "azure-d"

  run-wm1:
    name: 'Run wm1'
    needs: [ build-wm1 ]
    runs-on: ubuntu-latest
    steps:
      - name: "Run wm1"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WM1_HOST }}
          port: ${{ secrets.WM1_PORT }}
          username: ${{ secrets.WM1_USERNAME }}
          key: ${{ secrets.WM1_KEY }}
          script: ./azure-d/run.sh
